### PR TITLE
filetype detect

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by kentookura** [comment]
I would prefer to do this by cleaning up this mess:
https://github.com/kentookura/forester.nvim/blob/cb4f75e42e532693f69f93530e35545b08306a5c/lua/forester.lua#L17-L28

Can do it tomorrow. If you want to do it, I would pull out all the stuff that's irrelevant to treesitter and make sure we don't confuse "tree" and "forester", I think the currenct code is mistaken

**Comment by kentookura** [comment]
I think we just need to change this:
https://github.com/kentookura/forester.nvim/blob/cb4f75e42e532693f69f93530e35545b08306a5c/lua/forester.lua#L17
to `{forester = "tree}`

**Comment by dannypsnl** [comment]
Do you mean `vim.filetype.add` is sufficient? Because I didn't see my status bar get any affects from the project for now.

**Comment by kentookura** [comment]
I get `filetype=forester` when I run `:set filetype?`. What status bar do you use?

**Comment by dannypsnl** [comment]
I use the lualine, and I have fetch the latest changes.

image

**Comment by kentookura** [comment]
Verified that it detects the filetype and displays it in lualine:
image

**Comment by kentookura** [comment]
BTW, I recommend this if you use devicons: 
`require("nvim-web-devicons").setup({ override_by_extension = { ["tree"] = { icon = "🌲" } } })`

**Comment by kentookura** [comment]
image

**Comment by dannypsnl** [comment]
Oops, I finally figure out, at some moment I misconfig my plugin that missing to invoke `forester.setup(...)`, now everything is work, thanks.

**Pull request closed without merging**
